# Generated by Django 3.0.4 on 2020-03-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productType',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
